config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  get 'users/login_form'
  get       'users/signin', to: 'users#signin',    as: 'user_signin'
  post      'users/create', to: 'users#create',    as: 'user_create'
  get 'posts/edit'
  get        'posts/index', to: 'posts#index',     as: 'posts_index'
  get          'posts/new', to: 'posts#new',       as: 'post_new'
  post      'psots/create', to: 'posts#create',    as: 'post_create'
  get 'posts/show'
  get '/',                  to: 'posts#top',       as: 'top'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
    validates :title, {presence: true, length: {maximum: 40}}
    validates :content, {presence: true, length: {maximum: 140}}
    validates :user_id, {presence: true}

    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    validates :name, {presence: true}
    validates :email, {presence: true, uniqueness: true}
    #validates :password, {presence: true}

    has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_current_user

    def set_current_user
        @current_user = User.find_by(id: session[:user_id])
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def edit
  end

  def index
  end

  def new
    @post = Post.new
  end

  def create
    @post = @current_user.posts.build(post_params)
    @post.image = "sample.image"

    if @post.save
      if params[:post][:image]
        @post.image = "#{@post.id}.jpg"
        post_image = params[:post][:image]
        File.binwrite("public/post_images/#{@post.image}", post_image.read)
        @post.save
      end
      flash[:notice] = "投稿を確認しました"
      redirect_to posts_index_path
    else
      render("posts/new")
    end

  end

  def show
  end

  def top
  end

  private
    def post_params
      params.require(:post).permit(:title, :content)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def login_form
  end

  def signin
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "新規登録しました"
      redirect_to posts_index_path
    else
      flash[:notice] = "入力内容が間違えています"
      render("users/signin")
      
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">


    <title>MyMenuApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render 'posts/navbar' %>
    </header>

    <% if flash[:notice] %>
      <div class = "flash">
        <%= flash[:notice] %>
      </div>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/posts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to("トップページ", top_path, class: "navbar-brand") %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to("新規投稿", post_new_path, class: "nav-link") %>
        </li>
        <li class="nav-item">
          <%= link_to("投稿一覧", posts_index_path, class: "nav-link") %>
        </li>
        <li class="nav-item">
          <%= link_to("会員登録", user_signin_path, class: "nav-link") %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/posts/edit.html.erb
<h1>Posts#edit</h1>
<p>Find me in app/views/posts/edit.html.erb</p>

app/views/posts/index.html.erb
<h1>Posts#index</h1>
<p>Find me in app/views/posts/index.html.erb</p>

app/views/posts/new.html.erb
<div class="container mx-auto" style="margin-top: 40px">
<h1>新規投稿</h1>

  <%= form_for(@post, url: post_create_path, multipart: true) do |f| %>
    <div class="post-new-label">
      <%= f.label :title %>
    </div>
      <%= f.text_field :title, class: "form-control" %>
    <div class="post-new-label">
      <%= f.label :content %>
    </div>
      <%= f.text_area :content, class: "form-control" %>
    <div class="post-new-label" >
      <%= f.label :image %>
    </div>
      <%= f.file_field :image %>
    <div class="post-new-label">
      <%= f.submit "投稿", class: "btn btn-primary post-new-label" %>
    </div>

  <% end %>
</div>

app/views/posts/show.html.erb
<h1>Posts#show</h1>
<p>Find me in app/views/posts/show.html.erb</p>

app/views/posts/top.html.erb
<h1>みんなの手抜きご飯</h1>
<p>手抜き料理を投稿して共有しよう</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/login_form.html.erb
<h1>Users#login_form</h1>
<p>Find me in app/views/users/login_form.html.erb</p>

app/views/users/signin.html.erb
<div class="container mx-auto" style="margin-top: 40px">
  <h1> 会員登録</h1>

    <%= form_for(@user, url:user_create_path, multipart: true) do |f| %>
        <div class="post-new-label">
        <%= f.label :"名前" %>
        </div>
            <%= f.text_field :name, class:"form-control" %>
        <div class="post-new-label">
        <%= f.label :"メールアドレス" %>
        </div>
            <%= f.text_area :email, class:"form-control" %>
        <div class="post-new-label">
        <%= f.label :"パスワード" %>
        </div>
            <%= f.text_field :password, class:"form-control" %>
        <div class="post-new-label">
        <%= f.label :"パスワード確認用" %>
        </div>
            <%= f.text_field :password_confirmation, class:"form-control" %>
        <div class="post-new-label">
        <%= f.submit "登録",  class:"btn btn-primary" %>
        </div>
    <% end %>
</div>